### ISSUE TITLE
Set starting laws appropriately

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#211]

**Comment by derHochmeister** [comment]
Conscription laws should be based upon a country's mobilization rate. With no mobilization and no army, the country should have _disarmed nation_ law, no mobilization but an army gets _volunteer only_, with mobilization happening the country gets _limited conscription_ and, finally, the country gets _extensive conscription_ with full mobilization.

Trade laws should be based upon tariffs. With tariffs lower than 0%, _free trade_ should be the law, tariffs between 0% and 50% gives _export focus_ and tariffs over 50% gives _limited exports_.

Economy laws should be based upon social and military spending. If a country spends none for both, _undisturbed isolation_ will be chosen, with social and military spending both below 10% we get _isolation_. For the others it depends. Any of the two spendings must be over 10%; if the social one is the one with most spend, _civilian economy_ is chosen, otherwise _early mobilization_.

I know this sounds hard to code, but that's how I would map them up.
