### ISSUE TITLE
Trouble creating country files

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#279]
https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-41#post-22882701

**Comment by hansvanmoer** [comment]
This seems an encoding issue.
Could be HoI4Country.cpp line 1635 but in the current build Output is changed to output (small case).
If the problem was found in the dev build it's possible I screwed something up in the path normalization.

**Comment by Idhrendur** [comment]
It seems likely to be an encoding issue, but a Windows one. I've asked for the save and mod used to try and figure out more. It's probably one of those 'international Windows is different from English-only encoding issues'. Which are frustrating because they're not documented and also because I can't replicate them on my Windows-only machine.

**Comment by hansvanmoer** [comment]
I'd be happy to test it on the machine's I've got laying around, if by some freak chance it proves reproduceable on Dutch or French versions of Windows :)

**Comment by Idhrendur** [comment]
That would be helpful. Placing a save on a path with non-ASCII characters should do the trick. It might just be some sets of them, I'm not sure. From what I understand, all international versions use the alternate processing from the American versions.

**Comment by Idhrendur** [comment]
Save and mod were provided on this post: https://forum.paradoxplaza.com/forum/index.php?threads/the-vic2-to-hoi4-converter-project-development-thread.915440/page-41#post-22902095

**Comment by hansvanmoer** [comment]
The country file in history/countries for the countries with tag X01 and X02 have odd names. 
There seem to be a lot of garbled strings in the Vic2 save as well. Since these appear associated with countries whose name probably can't be represented in ISO 8859-15 this may be intentional. Does Vic2 use a mechanism to represent non-latin characters in the save files ?

For example, it seems almost all references to a country called Pandya or Pandyas (and events associated with it) have garbled string values in the Vic2 save file.

**Comment by Idhrendur** [comment]
The relevant garbling was in the localisation (which becomes countryFilename). I had to add a convert8859_15toASCII function to the Utils to fix it (along with some hard-coded removal of bad characters).
