### ISSUE TITLE
Update to EU4 version 1.23

### ISSUE THREAD

**Issue by kratostatic** [Idhrendur/paradoxGameConverters#314]
This will obviously be needed once 1.23 comes out.

As whatever problems this update will cause us are not yet known I was thinking we could also use the comment thread on this to discuss what we want to do for this release and just in general what we want to do with the converter next.

**Comment by kratostatic** [comment]
Thoughts for what to do in this.

As far as I know there are 3 big potential projects:

M&T ( #315 )
NMM ( #38 )
improving colonial stuff (a whole bunch of stuff, including #49 , #52 , #317 )

I want to do all of these.  If we try to do all of these now we'll go insane and never finish any of them so I think we should pick one and concentrate on it.  If we finish we can move on to another - we've got time until the next update of EU4. and even then these can always wait until the next version.

Are there any other things I've missed?

**Comment by derHochmeister** [comment]
I'd include CK2 Tibetan titles as well, but I am unsure they'll be added by the 1.23 EU4 version ( https://github.com/Idhrendur/paradoxGameConverters/issues/268 ).

As well, I'll add cultural and religious support for the CK2 mod WTWSMS.

**Comment by kratostatic** [comment]
Greatstuff!  I'd added the Tibetan Titles to the milestone but as you say we don't know which is going to be released first.

Of the three big things I mentioned which do you want to concentrate on?

Also I don't know if you've seen the most recent EU4 dev diary but 1.23 is adding new provinces and tags in Arabia, Egypt, Anatolia and the Caucasus.

**Comment by derHochmeister** [comment]
1. Currently, I'm on a stalemate for testing if my M&T updates would work, as the converter seems unable to handle the new tech groups and units, crashing before creating any file. I updated with their data (and with WTWSMS's) religious, governmental, cultural and colonial nations mappings.

2. But I also tried to incorporate most of NNM as well. I made sure that all files of NNM but one would correctly overlap without problems. The only file I did not work on is the common/countries.txt

3. As well, I noticed that the cultures' localisation file could be improved, as many of the entries don't exist.

4. I already saw the 1.23 diary. I decided to prepare by thinking up of the flags. For Medina, I simply re-designed the flag for d_medina, basing on the CK2 Muhammad symbol.

![image](https://user-images.githubusercontent.com/24550392/28995310-41186d36-79e6-11e7-974f-f1f4260b499e.png)

I'll show you the flags I made. Najran is actually flagless, due to no possibility of finding any possible symbol. I'll have to wait for EU team to release, probably. Yemen and Aden will be switched, so Aden will have to get an own tag/flag. Obviously, they'll be adapted if the EU4 flag used differs.

![image](https://user-images.githubusercontent.com/24550392/28995290-a703c7d6-79e5-11e7-8fbe-e74eb1bcd22d.png)

I'll tell you my sources for most flags.
-Rassids, ruling dynasty of Yemen. I used a monarchist ensign for them, Yemenite flags for the rest
-Hadramawt, Mahra, Aden. They were emirates under the British ensign in OTL, so I used their historical flags, editing them for the communist and fascist entries.
-Mikhlaf. I'm unsure of this, I just saw it in "List of states in 1916~1920" as "Emirate of Upper Asir". I'm unsure it refers to Mikhlaf, but it is pretty probable. For communist and fascist, total fantasy.
-Najran. No symbol used, I'll use one as soon as I discover the flag EU team is using.
-Jas. They will found Dubai, so I adapted the Dubaite flag for them.
-Dawasir, Anizah, Fadl. Bedouin tribes with no known symbol, I simply used their EU map color, with their name on the flag. Fascist simply removes the name, adding swords instead. Communist recolors according to palette.

**Comment by kratostatic** [comment]
Sorry forgot to say those flags look great, and I think that even if the EU4 ones end up being very different then the Fascist and Communist ones should still work anyway.

**Comment by IohannesIohannium** [comment]
The patch is out, by some days I should have a proper upgrade for the converter, which will fix also a lot of other things.

**Comment by kratostatic** [comment]
Done by 1.0H, finally!
