### ISSUE TITLE
Get rid of completely uncivilised worlds

### ISSUE THREAD

**Issue by kratostatic** [Idhrendur/paradoxGameConverters#319]
Games converted from before 1570 or so will have no civilised nations at all, because of how the current civilised algorithm works with institutions - 7 institutions are assumed.

This is obviously a fairly major bug as a non-negligable number of users want to convert fairly short games (including some trying to use the 1444 start date and converting straight to Vicky2).

**Comment by derHochmeister** [comment]
Edit the algorithm so that it is based on who has most institutions.

Like, the most institution'd country has 5? Base the algorithm on it. It has only 2? Base the algorithm so.

This way, the world should be civilized by someone at least. But better add a part to the algorithm to not civilize non-western and non-eastern unless they have 6 or more institutions, even if there aren't enough in the whole world.

**Comment by kratostatic** [comment]
Yeah, that was what I thought as well.  Luckily that should be easy to do - it's basically how it gets the top tech already.

The current version of the civilisation algorithm doesn't actually use tech groups at all as I didn't think they changed anything other than unit types these days.  Do they do something else?  I'll add them back in if they actually change something.

**Comment by kratostatic** [comment]
fixed in 8316f1246d3a2447030a892f6ac118f027d4bfa7
