### ISSUE TITLE
Kingdom of America

### ISSUE THREAD

**Issue by IohannesIohannium** [Idhrendur/paradoxGameConverters#359]
The issue is, USA will always be converted into HoI4 as "Kingdom of America" if democratic. This makes almost no sense, and I think we should add a row of code to avoid it happen, as US may be a republic as well.

EDIT: It happens with any country that is democratic and has a special monarchic name.

I propose the converter to look up if it is a monarchy of not before choosing such name, as using "Empire of Mexico" for a Republic looks awkward.

**Comment by Idhrendur** [comment]
Okay, I've looked this over. This happens because the localisations are simply pulled from the Vic2 government types and applied to the HoI4 government types. But the prussian constitutionalism government mappings are after the democracy mappings, so override the localisations.

Clearly, I'll have to put more smarts into how the localisations are generated.

**Comment by Idhrendur** [comment]
Fixed in dc68abc35d1289d252809d13719b65c1b15d92bb
