### ISSUE TITLE
Consider setting a default graphical culture

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#423]
Right now if there isn't a match, it'll default to blank. Should we instead default to a defined one?

FWIW, no-one responded to this question on the forums.

**Comment by IohannesIohannium** [comment]
HoI4 vanilla uses Anglophone names and portraits as default, mainly because that was the main power in the world. I'd say that, if no culture is found, names and portraits should default to the ones of the N°1 Great Power or, if it is to hard to mod, let the player choose between French and English.
