### ISSUE TITLE
Relationship values are not properly imported

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#46]
Relationship values expect a leaf called "value" in EU4, but this is not actually there. In older saves, cached_sum seems to fill that role, and it is uncertain if any value is saved in current saves.

In addition, there is no process for merging to individual relationship values in EU4 to bilateral values in Vic2. It is uncertain what Vic2 does with differing values.

**Comment by derHochmeister** [comment]
The save game in EU4 saves relationship values this way.

(Under the country X)
active_relations = {
 (country Y)={
  opinion={
(not so useful)
  }
 **cached_sum=[value]**
trust_value=x
last_war=xx.yy.zzzz
attitude="[attitude]"
 }
}

Sometimes, the cached_sum value doesn't exist because there has been no opinion modifier rather than the normal basic religious ones.

I think that EU4 relation values should be averaged to form a bilateral Vic2 value. (With averging, I mean doing `{ (EU4) XtoY + (EU4) YtoX } / 2 = (Vic2) X<->Y`)

**Comment by kratostatic** [comment]
Ok so I believe I've just fixed the getting of the actual relationship value (I think it's fair to say if there are no modifiers then calling relations 0 between the countries is fine, the religion modifiers aren't normally that big anyway).

The averaging may be a bit trickier due to the way the code is set up.  I will see what happens with bilateral values once I test this on some real saves.

I will close this for now but I will reopen once 1.0G is released.
